---
metadata:
  '4400':
    sort_title: 4400 2021
  Agents of S.H.I.E.L.D.:
    label: Kids
    sort_title: Marvel 2013-09-24
  AmazingStories1:
    sort_title: Amazing Stories 1985-09-29
    title: Amazing Stories
    year: 1985
  AmazingStories2:
    sort_title: Amazing Stories 2020-03-06
    title: Amazing Stories
    year: 2020
  Andor:
    sort_title: Star Wars 2022-09-20
  I Am Groot:
    sort_title: Marvel 2022-08-10
  Louis Theroux Interviews...:
    sort_title: Louis Theroux 2022-10-25
  Naruto:
    label: Kids
    sort_title: Naruto 2002
  'Naruto: Shippuden':
    label: Kids
    sort_title: Naruto 2007
  Obi-Wan Kenobi:
    sort_title: Star Wars 2022-05-27
  Quantum Leap 1989:
    sort_title: Quantum Leap 1989
    title: Quantum Leap
    year: 1989
  Quantum Leap 2022:
    sort_title: Quantum Leap 2022
    title: Quantum Leap
    year: 2022
  ShamelessUK:
    sort_title: Shameless 2004
    title: Shameless
    year: 2004
  ShamelessUS:
    sort_title: Shameless 2011
    title: Shameless
    year: 2011
  'She-Hulk: Attorney at Law':
    sort_title: Marvel 2022-08-17
  Star Trek:
    sort_title: Star Trek 1966-09-08
  'Star Trek: Deep Space Nine':
    sort_title: Star Trek 1993-01-03
  'Star Trek: Discovery':
    sort_title: Star Trek 2017-09-24
  'Star Trek: Enterprise':
    sort_title: Star Trek 2001-09-26
  'Star Trek: Lower Decks':
    sort_title: Star Trek 2020-07-23
  'Star Trek: Picard':
    sort_title: Star Trek 2020-01-23
  'Star Trek: Prodigy':
    sort_title: Star Trek 2021-10-28
  'Star Trek: Strange New Worlds':
    sort_title: Star Trek 2022-05-05
  'Star Trek: The Animated Series':
    sort_title: Star Trek 1973-09-08
  'Star Trek: The Next Generation':
    sort_title: Star Trek 1987-09-26
  'Star Trek: Voyager':
    sort_title: Star Trek 1995-01-16
  'Star Wars: The Clone Wars':
    sort_title: Star Wars 2008-10-03
  Stargate Atlantis:
    sort_title: Stargate 2004-07-16
  Stargate Origins:
    sort_title: Stargate 2018-02-15
  Stargate SG-1:
    sort_title: Stargate 1997-07-27
  Stargate Universe:
    sort_title: Stargate 2009-10-02
  'Stargate: Infinity':
    sort_title: Stargate 2002-09-14
  The 4400:
    sort_title: 4400 2004
  The Book of Boba Fet:
    sort_title: Star Wars 2021-12-29
  The Mandalorian:
    sort_title: Star Wars 2019-11-12
  WWE 24:
    sort_title: WWE 2015-01-30
  WWE Monday Night RAW:
    sort_title: WWE 1993-01-11
  WWE Rivals:
    sort_title: WWE 2022-07-10
  WWF SmackDown!:
    sort_title: WWE 1999-04-27
