---
metadata:
  '24':
    sort_title: 24 2001-11-06
  '24: Legacy':
    sort_title: 24 2017-01-09
  '4400':
    sort_title: 4400 2021
  Agent Carter:
    sort_title: Marvel 2015-01-06
  Agents of S.H.I.E.L.D.:
    label: Kids
    sort_title: Marvel 2013-09-24
  'All Elite Wrestling: Dynamite':
    sort_title: All Elite Wrestling 2019
  'All Elite Wrestling: Rampage':
    sort_title: All Elite Wrestling 2021
  AmazingStories1:
    sort_title: Amazing Stories 1985-09-29
    title: Amazing Stories
    year: 1985
  AmazingStories2:
    sort_title: Amazing Stories 2020-03-06
    title: Amazing Stories
    year: 2020
  American Chopper:
    sort_title: American Chopper 2002
  'American Chopper: Senior vs Junior':
    sort_title: American Chopper 2010
  Andor:
    sort_title: Star Wars 2022-09-20
  Around the World in 80 Days Palin:
    sort_title: Michael Palin 1989-10-11
    title: Around the World in 80 Days
    year: 1989
  'Astonishing X-Men: Gifted':
    sort_title: X-Men 2009-10-27
  Avengers Assemble:
    sort_title: Marvel 2013-05-26
  Bang, Bang, It's Reeves and Mortimer:
    sort_title: Vic Reeves 1999-01-01
  Batman of the Future:
    sort_title: Batman 1999-01-10
  'Batman: The Animated Series':
    sort_title: Batman 1992-09-05
  'Batman: The Brave and The Bold':
    sort_title: Batman 2008-11-14
  Beavis and Butt-Head:
    sort_title: Beavis and Butt-Head 1993
  Beware the Batman:
    sort_title: Batman 2013-07-13
  Blue Planet II:
    sort_title: Blue Planet 2017-10-29
  Brazil with Michael Palin:
    sort_title: Michael Palin 2012-10-24
  Cloak & Dagger:
    sort_title: Marvel 2018-06-07
  Cowboy Beebop Anime:
    sort_title: Cowboy Beebop 1998-04-03
    title: Cowboy Beebop
    year: 1998
  Cowboy Beebop Live:
    sort_title: Cowboy Beebop 2021-11-19
    title: Cowboy Beebop
    year: 2021
  Daredevil:
    sort_title: Marvel 2015-04-10
  Dexter:
    sort_title: Dexter 2006-10-01
  'Dexter: New Blood':
    sort_title: Dexter 2021-11-07
  Ducktales 1987:
    sort_title: Ducktales 1987-09-07
    title: Ducktales
    year: 1987
  Ducktales 2017:
    sort_title: Ducktales 2017-08-12
    title: Ducktales
    year: 2017
  Floyd on Africa:
    sort_title: Floyd 1996-04-23
  Floyd's American Pie:
    sort_title: Floyd 1989-10-10
  Forged in Fire:
    sort_title: Forged in Fire 2015
  'Forged in Fire: Beat the Judges':
    sort_title: Forged in Fire 2020
  'Forged in Fire: Knife or Death':
    sort_title: Forged in Fire 2018
  Full Circle with Michael Palin:
    sort_title: Michael Palin 1997-08-10
  Ghosts UK:
    sort_title: Ghosts 2019
    title: Ghosts
    year: 2019
  Ghosts US:
    sort_title: Ghosts 2021
    title: Ghosts
    year: 2021
  Going Postal:
    sort_title: Discworld 2010-05-30
  Hawkeye:
    sort_title: Marvel 2021-11-24
  Helstrom:
    sort_title: Marvel 2020-10-15
  Himalaya with Michael Palin:
    sort_title: Michael Palin 2004-10-03
  I Am Groot:
    sort_title: Marvel 2022-08-10
  Inhumans:
    sort_title: Marvel 2017-09-01
  Iron Fist:
    sort_title: Marvel 2017-03-17
  James May's Man Lab:
    sort_title: James May 2010-10-31
  'James May: Our Man in...':
    sort_title: James May 2020-01-02
  'James May: The Reassembler':
    sort_title: James May 2016-04-04
  Jessica Jones:
    sort_title: Marvel 2015-11-20
  Legion:
    sort_title: Marvel 2017-02-08
  Lego Masters UK:
    sort_title: Lego Masters 2017-08-24
    title: Lego Masters
    year: 2017
  Lego Masters US:
    sort_title: Lego Masters 2020-02-05
    title: Lego Masters
    year: 2020
  Long Way Down:
    sort_title: Long Way 2007-10-28
  Long Way Round:
    sort_title: Long Way 2004-10-18
  Long Way Up:
    sort_title: Long Way 2020-09-18
  Louis Theroux:
    sort_title: Louis Theroux 0000
  Louis Theroux Interviews...:
    sort_title: Louis Theroux 2022-10-25
  Louis Theroux Met:
    sort_title: Louis Theroux 2000-04-13
  Louis Theroux's Altered States:
    sort_title: Louis Theroux 2018-11-04
  Louis Theroux's Forbidden America:
    sort_title: Louis Theroux 2022-02-13
  Louis Theroux's LA Stories:
    sort_title: Louis Theroux 2014-03-23
  'Louis Theroux: By Reason of Insanity':
    sort_title: Louis Theroux 2015-03-22
  'Louis Theroux: Dark State':
    sort_title: Louis Theroux 2017-10-08
  'Louis Theroux: Life on the Edge':
    sort_title: Louis Theroux 2020-09-06
  'Louis Theroux: Miami Mega Jail':
    sort_title: Louis Theroux 2011-05-22
  'Louis Theroux: Weird Weekends':
    sort_title: Louis Theroux 1998-01-15
  Luke Cage:
    sort_title: Marvel 2016-09-30
  M.O.D.O.K.:
    sort_title: Marvel 2021-05-21
  Marvel Rising:
    sort_title: Marvel 2018-08-13
  'Marvel Studios: Assembled':
    sort_title: Marvel 2021-03-12
  Marvel's Hit-Monkey:
    sort_title: Marvel 2021-11-17
  Michael Palin in North Korea:
    sort_title: Michael Palin 2018-09-20
  Michael Palin's Hemingway Adventure:
    sort_title: Michael Palin 1999-05-03
  Mike Judge's Beavis and Butt-Head:
    sort_title: Beavis and Butt-Head 2022
  Monty Python's Flying Circus:
    sort_title: Monty Python 1969-10-05
  'Monty Python: Almost The Truth (The Lawyer''s Cut)':
    sort_title: Monty Python 2009-10-18
  Moon Knight:
    sort_title: Marvel 2022-03-30
  Ms. Marvel:
    sort_title: Marvel 2022-06-08
  Narcos:
    sort_title: Narcos 2015-08-28
  'Narcos: Mexico':
    sort_title: Narcos 2018-11-16
  Naruto:
    label: Kids
    sort_title: Naruto 2002
  'Naruto: Shippuden':
    label: Kids
    sort_title: Naruto 2007
  New Europe:
    sort_title: Michael Palin 2007-09-16
  Obi-Wan Kenobi:
    sort_title: Star Wars 2022-05-27
  Planet Earth:
    sort_title: Planet Earth 2006-02-27
  Planet Earth II:
    sort_title: Planet Earth 2016-11-06
  Pole to Pole:
    sort_title: Michael Palin 1992-10-21
  Quantum Leap 1989:
    sort_title: Quantum Leap 1989
    title: Quantum Leap
    year: 1989
  Quantum Leap 2022:
    sort_title: Quantum Leap 2022
    title: Quantum Leap
    year: 2022
  Red Dwarf:
    sort_title: Red Dwarf 1988-02-15
  'Red Dwarf: The First Three Million Years':
    sort_title: Red Dwarf 2020-08-06
  Runaways:
    sort_title: Marvel 2017-11-21
  SGU Stargate Universe:
    sort_title: Stargate 2009-10-02
  Sahara with Michael Palin:
    sort_title: Michael Palin 2002-10-13
  Shameless UK:
    sort_title: Shameless 2004
    title: Shameless
    year: 2004
  Shameless US:
    sort_title: Shameless 2011
    title: Shameless
    year: 2011
  'She-Hulk: Attorney at Law':
    sort_title: Marvel 2022-08-17
  Soul Music:
    sort_title: Discworld 1997-06-06
  Spider-Man:
    sort_title: Spider-Man 2017-06-30
  Star Trek:
    sort_title: Star Trek 1966-09-06
  'Star Trek: Deep Space Nine':
    sort_title: Star Trek 1993-01-03
  'Star Trek: Discovery':
    sort_title: Star Trek 2017-09-24
  'Star Trek: Enterprise':
    sort_title: Star Trek 2001-09-25
  'Star Trek: Lower Decks':
    sort_title: Star Trek 2020-08-06
  'Star Trek: Picard':
    sort_title: Star Trek 2020-01-23
  'Star Trek: Prodigy':
    sort_title: Star Trek 2021-10-28
  'Star Trek: Strange New Worlds':
    sort_title: Star Trek 2022-05-05
  'Star Trek: The Animated Series':
    sort_title: Star Trek 1973-09-08
  'Star Trek: The Next Generation':
    sort_title: Star Trek 1987-09-26
  'Star Trek: Voyager':
    sort_title: Star Trek 1995-01-16
  'Star Wars: The Clone Wars':
    sort_title: Star Wars 2008-08-15
  Stargate Origins:
    sort_title: Stargate 2018-02-15
  Stargate SG-1:
    sort_title: Stargate 1997-07-27
  'Stargate: Atlantis':
    sort_title: Stargate 2004-07-16
  'Stargate: Infinity':
    sort_title: Stargate 2002-09-14
  Taskmaster:
    sort_title: Taskmaster 2015-07-28
  Taskmaster (New Zealand):
    sort_title: Taskmaster 2020-10-21
  'Taskmaster: Champion of Champions':
    sort_title: Taskmaster 2017-12-13
  Terry Pratchett's Hogfather:
    sort_title: Discworld 2006-12-17
  The 4400:
    sort_title: 4400 2004
  The Batman:
    sort_title: Batman 2004-09-11
  The Blue Planet:
    sort_title: Blue Planet 2001-09-12
  The Book of Boba Fett:
    sort_title: Star Wars 2021-06-08
  The Colour of Magic:
    sort_title: Discworld 2008-03-23
  The Defenders:
    sort_title: Marvel 2017-08-18
  The Falon and the Winter Soldier:
    sort_title: Marvel 2021-03-19
  The Gifted:
    sort_title: Marvel 2017-10-01
  The Mandalorian:
    sort_title: Star Wars 2019-11-12
  The New Batman Adventures:
    sort_title: Batman 1997-09-13
  The Office UK:
    sort_title: Office 2001-07-09
    title: The Office
    year: 2001
  The Office US:
    sort_title: Office 2005-03-24
    title: The Office
    year: 2005
  The Punisher:
    sort_title: Marvel 2017-11-17
  The Smell of Reeves and Mortimer:
    sort_title: Vic Reeves 1993-09-21
  The Stand 1994:
    sort_title: Stand 1994-05-08
    title: The Stand
    year: 1994
  The Stand 2020:
    sort_title: Stand 2020-12-16
    title: The Stand
    year: 2020
  The War of the Worlds:
    sort_title: War of the Worlds 2019-10-05
  The Watch:
    sort_title: Discworld 2020-12-31
  Thundercats:
    sort_title: Thundercats 2011-07-29
    title: Thundercats
    year: 2011
  Thundercats 1985:
    sort_title: Thundercats 1985-01-23
    title: Thundercats
    year: 1985
  Thundercats Roar:
    sort_title: Thundercats 2020-01-10
  Toy Stories:
    sort_title: James May 2009-10-27
  Trailer Park Boys:
    sort_title: Trailer Park Boys 2001-04-22
  'Trailer Park Boys: Out of the Park':
    sort_title: Trailer Park Boys 2016-10-28
  'Trailer Park Boys: The Animated Series':
    sort_title: Trailer Park Boys 2019-03-31
  Ultimate Spider-Man:
    sort_title: Spider-Man 2012-04-01
  Vic Reeves Big Night Out:
    sort_title: Vic Reeves 1990-05-25
  Vic and Bob's Big Night Out:
    sort_title: Vic Reeves 2018-11-28
  WWE 24:
    sort_title: WWE 2015-01-30
  WWE Monday Night RAW:
    sort_title: WWE 1993-01-11
  WWE Rivals:
    sort_title: WWE 2022-07-10
  WWF SmackDown!:
    sort_title: WWE 1999-04-27
  Wandavision:
    sort_title: Marvel 2021-01-15
  War of the Worlds:
    sort_title: War of the Worlds 2019-10-28
  What If...?:
    sort_title: Marvel 2021-08-11
  Whose Line Is It Anyway? UK:
    sort_title: Whose Line is it Anyway 1988-09-23
    title: Whose Line is it Anyway?
    year: 1988
  Whose Line Is It Anyway? US 1998:
    sort_title: Whose Line is it Anyway 1998-08-05
    title: Whose Line is it Anyway?
    year: 1998
  Whose Line Is It Anyway? US 2013:
    sort_title: Whose Line is it Anyway 2013-07-16
    title: Whose Line is it Anyway?
    year: 2013
  Wilfred AUS:
    sort_title: Wilfred 2007-03-19
    title: Wilfred
    year: 2007
  Wilfred US:
    sort_title: Wilfred 2011-06-23
    title: Wilfred
    year: 2011
  Wyrd Sisters:
    sort_title: Discworld 1997-05-18
  X-Men:
    sort_title: X-Men 1992-10-31
  'X-Men: Evolution':
    sort_title: X-Men 2000-11-04
