---
overlays:
  language:
    overlay:
      back_color: '#00000099'
      back_height: 105
      back_radius: 30
      back_width: 300
      font: fonts/Inter-Medium.ttf
      font_color: '#FFFFFF'
      font_size: 73
      horizontal_align: center
      horizontal_offset: 0
      name: text(Foreign)
      vertical_align: top
      vertical_offset: 15
    plex_search:
      all:
        audio_language.not: English